Banner close & breadcrumb url change
yournextstore/yournextstore pull request #63
Opened 2024-11-05 17:57 UTC by CallMeSlinky

Here are two changes. I'm not sure if the breadcrumb for "/" is intended to be like that, but I thought it'd make more sense to actually view all the products. I also added a close button to the banner but this change maybe controversial.  😁

2024-11-05 17:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yournextstore/yournextstore?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yournextstore/yournextstore?pullRequest=63) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yournextstore/yournextstore?pullRequest=63) it.</sub>

2024-11-05 22:19 UTC, zaiste requested changes

2024-11-05 22:19 UTC, zaiste commented on src/ui/banner.tsx
> +	};
@CallMeSlinky could you add early `return` instead of the `isOpen && ...` syntax?

2024-11-05 22:19 UTC, zaiste commented
@CallMeSlinky thanks for the contribution! the banner is temporary but we can add it to the codebase as an example

2024-11-05 23:30 UTC, zaiste commented
@CallMeSlinky great! 

just a nitpick: using `git rebase` on a PR with `main` won’t create those `Merge branch ...` commits.

2024-11-05 23:30 UTC, merged

2024-11-05 23:35 UTC, CallMeSlinky commented
> @CallMeSlinky great!
> 
> just a nitpick: using `git rebase` on a PR with `main` won’t create those `Merge branch ...` commits.

I see, sorry! I'm quite new to contributing on Github. I shall read up on this more, as it's quite daunting! 😨

2024-11-06 01:40 UTC, zaiste commented
@CallMeSlinky no worries! you did great!